# Welcome to Jekyll!

# Site settings
title: Odditypark
email: udtrokia@gmail.com
description: >- 
  Take your protein pills and put your helmet on.

# Build settings
theme: jekyll-theme-clearloop
remote_theme: clearloop/jekyll-theme-clearloop
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag

# Posts
format: "%b %-d, %Y"
